### ISSUE TITLE
Vonage Voyagers Application - Leverage serverless for the webhooks

### ISSUE THREAD

**Issue by nuxero** [Nexmo/amazon-transcribe-call#10]
Hi. I'm applying for Vonage Voyagers program so I'm opening this issue to suggest a improvement.

Deploying the webhooks would require to set up and maintain a server with node, which will charge even if there is no requests goin through. One way to solve this is to deploy webhooks using a serverless approach.

By deploying webhooks using AWS API Gateway + Lambda, AWS would only charge when they are executed and recordings can be stored on S3. Then, SES can be used to notify a user that the transcribe process is finished and it can include the download link. 

I did something similar in the company I work for.

**Comment by phazonoverload** [comment]
Hey @nuxero - thanks for this. 

As someone who loves serverless I totally hear your suggestion. However, this suggestion is essentially to rewrite this application entirely to work in the context of serverless. 

Do you have any feedback on this codebase? Or a feature request that can be implemented with the existing stack?

**Comment by phazonoverload** [comment]
Hey @nuxero I just wanted to check in and see if you had any other questions about the Voyagers exercise? Looking forward to reviewing it 😀

**Comment by nuxero** [comment]
Hello, @phazonoverload.

The idea would be to keep the logic of the webhooks, only thing that changes is that instead of being contained inside an express application these are on Serverless Framework handlers functions.

The voyagers exercise only required creating a Issue but I'll be happy to create a PR for this repo, however as you said, as this is essentially a rewrite it probably doesn't make sense as the objective of this sample is to show the logic behind transcribing a call and not implementing a serverless solution.

If you're interested on creating a separate repo and/or content for that I'll be happy to help, I have some experience creating this kind of things 😁

**Comment by phazonoverload** [comment]
100% no need to write any code - this issue is fine, I just had some additional questions 😄 

I understand your suggestion, but I'm keen to understand if there are any practical suggestions which could be made to this codebase, such as:

- Is there somewhere that a chunk of code could be improved for performance, readability, or maintainability? 
- Is there anything that could be better explained in the README? 
- Is there anything you would do differently? If so, why?

**Comment by nuxero** [comment]
My suggestions only attempts to answer the last question. What I would do differently is storing the webhooks logic in lambda functions because that way I'd get rid of the necessity of deploying and mantaining a server and optimize costs (in a production-like implementation). There are already some lambda functions using the Serverless Framework in this codebase so in my opinion it would be just matter of moving the relevant code there

**Comment by phazonoverload** [comment]
That's very true, though I was more interested in progressive enhancements over a complete refactor and change of approach. I'm going to accept this exercise and follow-up with an email shortly 😄
